CREATE TABLE tb_mall_refund_detail (
    refund_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '退款ID',
    refund_sn VARCHAR(64) NOT NULL COMMENT '退款单号',
    return_order_id BIGINT COMMENT '退货订单ID',
    order_id BIGINT NOT NULL COMMENT '原订单ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    refund_amount DECIMAL(10,2) NOT NULL COMMENT '退款金额',
    refund_type TINYINT NOT NULL COMMENT '退款类型 1-仅退款 2-退货退款',
    refund_status TINYINT DEFAULT 0 COMMENT '退款状态 0-待处理 1-退款中 2-退款成功 3-退款失败',
    refund_reason_type TINYINT COMMENT '退款原因类型 1-质量问题 2-订单取消 3-缺货 4-其他',
    refund_reason VARCHAR(255) COMMENT '退款原因',
    refund_method TINYINT COMMENT '退款方式 1-原路返回 2-退到余额',
    refund_account VARCHAR(64) COMMENT '退款账号',
    refund_pay_sn VARCHAR(64) COMMENT '退款流水号',
    refund_time DATETIME COMMENT '退款时间',
    admin_note VARCHAR(255) COMMENT '管理员备注',
    handle_time DATETIME COMMENT '处理时间',
    handle_man VARCHAR(50) COMMENT '处理人',
    delete_flag TINYINT DEFAULT 0 COMMENT '是否删除 0-未删除 1-已删除',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_order_id (order_id),
    INDEX idx_refund_sn (refund_sn),
    INDEX idx_user_id (user_id)
) COMMENT='退款详情表';