CREATE TABLE tb_mall_order (
    order_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '订单ID',
    order_sn VARCHAR(64) NOT NULL COMMENT '订单编号',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    order_total_amount DECIMAL(10,2) NOT NULL COMMENT '订单总金额',
    order_original_amount DECIMAL(10,2) NOT NULL COMMENT '订单原始金额',
    order_coupon_discount DECIMAL(10,2) DEFAULT 0 COMMENT '优惠券优惠金额',
    order_promotion_discount DECIMAL(10,2) DEFAULT 0 COMMENT '活动优惠金额',
    order_actual_amount DECIMAL(10,2) NOT NULL COMMENT '实际支付金额',
    order_coupon_id BIGINT COMMENT '使用的优惠券ID',
    order_promotion_id BIGINT COMMENT '参与的活动ID',
    order_status TINYINT DEFAULT 0 COMMENT '订单状态 0-待支付 1-已支付 2-已发货 3-已完成 4-已取消 5-退款中 6-部分退款 7-全部退款',
    order_pay_type TINYINT DEFAULT 0 COMMENT '支付方式 0-未支付 1-支付宝 2-微信 3-银行卡',
    order_pay_sn VARCHAR(64) COMMENT '支付流水号',
    order_pay_time DATETIME COMMENT '支付时间',
    order_ship_time DATETIME COMMENT '发货时间',
    order_complete_time DATETIME COMMENT '完成时间',
    order_cancel_time DATETIME COMMENT '取消时间',
    order_cancel_reason VARCHAR(255) COMMENT '取消原因',
    order_auto_cancel_time DATETIME COMMENT '自动取消时间',
    order_receiver_name VARCHAR(50) COMMENT '收货人姓名',
    order_receiver_phone VARCHAR(20) COMMENT '收货人手机号',
    order_receiver_province VARCHAR(20) COMMENT '省',
    order_receiver_city VARCHAR(20) COMMENT '市',
    order_receiver_district VARCHAR(20) COMMENT '区',
    order_receiver_address VARCHAR(255) COMMENT '详细地址',
    order_remark VARCHAR(255) COMMENT '订单备注',
    express_company VARCHAR(50) COMMENT '快递公司',
    express_number VARCHAR(50) COMMENT '快递单号',
    refund_amount DECIMAL(10,2) DEFAULT 0 COMMENT '已退款金额',
    delete_flag TINYINT DEFAULT 0 COMMENT '是否删除 0-未删除 1-已删除',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id),
    INDEX idx_order_sn (order_sn),
    INDEX idx_order_status (order_status),
    INDEX idx_create_time (create_time)
) COMMENT='订单主表';