CREATE TABLE tb_mall_order_item (
    order_item_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '订单商品详情ID',
    order_id BIGINT NOT NULL COMMENT '订单ID',
    series_id BIGINT COMMENT '商品系列ID',
    model_id BIGINT NOT NULL COMMENT '商品型号ID',
    sku_id BIGINT NOT NULL COMMENT '商品SKU ID',
    model_name VARCHAR(100) NOT NULL COMMENT '型号名称',
    sku_name VARCHAR(100) NOT NULL COMMENT 'SKU名称',
    goods_main_image VARCHAR(255) COMMENT '商品主图',
    original_price DECIMAL(10,2) NOT NULL COMMENT '原始单价',
    actual_price DECIMAL(10,2) NOT NULL COMMENT '实际单价（考虑活动后）',
    goods_num INT NOT NULL COMMENT '购买数量',
    goods_total_price DECIMAL(10,2) NOT NULL COMMENT '该商品总价',
    promotion_id BIGINT COMMENT '参与的活动ID',
    promotion_amount DECIMAL(10,2) DEFAULT 0 COMMENT '活动优惠金额',
    delete_flag TINYINT DEFAULT 0 COMMENT '是否删除 0-未删除 1-已删除',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_order_id (order_id),
    INDEX idx_sku_id (sku_id)
) COMMENT='订单商品详情表';