CREATE TABLE tb_mall_spec (
    spec_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '规格ID',
    spec_name VARCHAR(50) NOT NULL COMMENT '规格名称', -- 如“尺寸”“颜色”“能效”
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='商品规格表';