CREATE TABLE tb_mall_spec_value (
    value_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '规格值ID',
    spec_id BIGINT NOT NULL COMMENT '规格ID',
    value_name VARCHAR(50) NOT NULL COMMENT '规格值名称', -- 如“55英寸”“红色”
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='商品规格值表';