CREATE TABLE tb_mall_sku_spec_relation (
    relation_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '关系ID',
    sku_id BIGINT NOT NULL COMMENT 'SKU ID',
    spec_id BIGINT NOT NULL COMMENT '规格ID',
    value_id BIGINT NOT NULL COMMENT '规格值ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='SKU规格关系表';