CREATE TABLE tb_mall_return_order (
    return_order_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '退货订单ID',
    return_order_sn VARCHAR(64) NOT NULL COMMENT '退货单号',
    order_id BIGINT NOT NULL COMMENT '原订单ID',
    order_item_id BIGINT NOT NULL COMMENT '订单商品ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    sku_id BIGINT NOT NULL COMMENT '商品SKU ID',
    return_num INT NOT NULL COMMENT '退货数量',
    return_amount DECIMAL(10,2) NOT NULL COMMENT '退货金额',
    return_reason_type TINYINT COMMENT '退货原因类型 1-质量问题 2-尺寸不合适 3-颜色与描述不符 4-收到商品与描述不符 5-其他',
    return_reason VARCHAR(255) COMMENT '退货原因描述',
    return_status TINYINT DEFAULT 0 COMMENT '退货状态 0-申请中 1-待寄回 2-已寄回 3-待验货 4-验货通过 5-验货不通过 6-已拒绝',
    return_express_company VARCHAR(50) COMMENT '退货快递公司',
    return_express_number VARCHAR(50) COMMENT '退货快递单号',
    return_address VARCHAR(255) COMMENT '退货地址',
    return_contact VARCHAR(50) COMMENT '退货联系人',
    return_phone VARCHAR(20) COMMENT '退货联系电话',
    admin_note VARCHAR(255) COMMENT '管理员备注',
    handle_time DATETIME COMMENT '处理时间',
    handle_man VARCHAR(50) COMMENT '处理人',
    receive_time DATETIME COMMENT '收货时间',
    receive_man VARCHAR(50) COMMENT '收货人',
    delete_flag TINYINT DEFAULT 0 COMMENT '是否删除 0-未删除 1-已删除',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_order_id (order_id),
    INDEX idx_return_order_sn (return_order_sn),
    INDEX idx_user_id (user_id)
) COMMENT='订单退货表';