CREATE TABLE tb_mall_goods_sku (
    sku_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'SKU ID',
    model_id BIGINT NOT NULL COMMENT '型号ID',
    sku_name VARCHAR(100) NOT NULL COMMENT 'SKU名称',
    sku_price DECIMAL(10,2) NOT NULL COMMENT 'SKU价格',
    sku_stock INT DEFAULT 0 COMMENT 'SKU库存',
    sku_code VARCHAR(50) COMMENT 'SKU编码',
    sku_status TINYINT DEFAULT 1 COMMENT '状态 1-上架 0-下架',
    delete_flag TINYINT DEFAULT 0 COMMENT '是否删除 0-未删除 1-已删除',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='商品SKU表';